WIP on fractalvalley F1 automation.

diff --git a/framework/aws/ec2_instance_feeder b/framework/aws/ec2_instance_feeder
--- a/framework/aws/ec2_instance_feeder
+++ b/framework/aws/ec2_instance_feeder
@@ -64,22 +64,21 @@
 #
 # connect/own:
 #
-#   Associate a new feeder with an instance. This instance may be running or stopped. The feeder is implicity fed
-#   when connected.
+#   Associate a new feeder with an instance. Feeder continues to run until "disconnected" or "dissociated". When not
+#   fed recently enough, the instance will be stopped by the feeder. It can be started at any time, but must first be fed.
 #
-#     > ec2_instance_feeder connect <feeder-file> <starvation-time> [<profile>] &
+#     > ec2_instance_feeder connect <feeder-file> <starvation-time> [<profile>]
 #
 #   Run this command after starting the instance, and with periodic feeding either already enabled or to be
-#   immediately begun. Creates a feeder file whose timestamp to monitor (containing the PID of this process). The feeder file name
-#   must be the instance ID (e.g. "i-12334567890abcdef0") to stop when starved. This process is the "feeder process" and it
-#   continues to run until disconnected or dissociated (see below). After the initialization
-#   banner is displayed on stdout (unless $debug is set below) the feeder file is created
-#   and no more output goes to stdout until termination. Errors report to stderr and the script keeps running until explicitly
-#   terminated (ideally by disconnect/dissociate commands, as below). If ungracefully killed by a signal, or by pulling the plug, the
-#   instance may be left running (and hopefully another feeder will be able to stop/terminate it) and the feeder file may remain.
+#   immediately begun. Creates a feeder file and launches a "feeder process" to monitor the feeder file's timestamp.
+#   The feeder file contains the PID of the feeder process, and the feeder file name must be the instance ID]
+#   (e.g. "i-12334567890abcdef0") to stop when starved. The feeder process continues to run until disconnected or
+#   dissociated (see below). It produces no output on stdout (unless $debug is set below); errors
+#   report to stderr. If ungracefully killed by a signal, or by pulling the plug, the instance may be left
+#   running (and hopefully another feeder will be able to stop/terminate it) and the feeder file may remain.
 #   This process intercepts common signals to delete the feeder file.
 #
-#   The distinction between connect and own is the starvation behavior:
+#   The distinction between "connect" and "own" is the starvation behavior:
 #      - Connect is for static  instances where the feeder is responsible for stopping    the instance on starvation.
 #      - Own     is for dynamic instances where the feeder is responsible for terminating the instance on starvation.
 #
@@ -190,40 +189,54 @@ watch_timeout=600  # Timeout for watching feeder file while instance is stopped.
 
 cmd_arg=$1
 feeder_file=$2
-inst_id=$( basename "$feederfile")
+inst_id=$( basename "$feeder_file")
 
 if [[ "$cmd_arg" == "disconnect" || "$cmd_arg" == "dissociate" || "$cmd_arg" == "starve" ]]
 then
   # Disconnect by deleting the feeder file. Make sure it looks like a feeder file, to be safe.
   if [[ -e "$feeder_file" ]]
   then
-    if [[ "$cmd_arg" == "disconnect" ]]
+    if [[ "$cmd_arg" == "disconnect" || "$cmd_arg" == "dissociate" ]]
     then
-      rm -f $feeder_file
-    else
-      if [[ "$cmd_arg" == "dissociate" ]]
+      pid=$( cat "$feeder_file" )
+      if [[ $pid =~ ^[[:digit:]]+$ ]]
       then
-        pid=$( cat "$feeder_file" )
-        if [[ $pid =~ ^[[:digit:]]+$ ]]
+        if [[ "$cmd_arg" == "dissociate" ]]
         then
           kill $pid
-          # SIGTERM will not be received until done waiting on the feeder file, so touch it (twice, since there's a race).
+          # SIGTERM will not be received until done waiting on the feeder file, so touch it (without creating it) (twice, since there's a race).
           touch -c -r "$feeder_file" "$feeder_file" >& /dev/null
           sleep 1
           touch -c -r "$feeder_file" "$feeder_file" >& /dev/null
         else
-          >&2 echo "$feeder_file doesn't look like a feeder file."
-          exit 1
+          # Disconnect.
+          rm -f $feeder_file
         fi
       else
-        # Starve
-        # Set file timestamp to be starved.
-        sec=$(( $starvation_time + 1 )); touch -c -d "$sec seconds ago" "$feeder_file"
+        >&2 echo "$0: $feeder_file doesn't look like a feeder file."
+        exit 1
       fi
+
+      # Wait for the process to die, since it may produce output.
+      cnt=10
+      while [[ $cnt > 0 ]] && ps -q "$pid" >& /dev/null
+      do
+        sleep 1
+        cnt=$((cnt-1))
+      done
+      if [[ $cnt == 0 ]]
+      then
+        >&2 echo "$0: Failed to terminate feeder process $pid"
+        exit 1
+      fi
+    else
+      # Starve
+      # Set file timestamp to be starved.
+      sec=$(( $starvation_time + 1 )); touch -c -d "$sec seconds ago" "$feeder_file"
     fi
     exit 0
   else
-    >&2 echo "$feeder_file does not exist."
+    >&2 echo "$0: $feeder_file does not exist."
     exit 1
   fi
 fi
@@ -269,7 +282,7 @@ if [[ "$cmd_arg" != "connect" && "$cmd_arg" != "own" ]]
 then
   if [[ "$cmd_arg" != "help" ]]
   then
-    >&2 echo "Illegal command argument: $cmd_arg"
+    >&2 echo "$0: Illegal command argument: $cmd_arg"
   fi
   usage
   exit 1
@@ -304,9 +317,9 @@ profile=$4
 #
 
 # Determine starvation time in hours.
-starvation_time_hrs=$( echo "scale=6; $starvation_time / 60 / 60 / 24" | bc || ( >&2 echo "Failed to compute starvation time in hours." && exit ) )
+starvation_time_hrs=$( echo "scale=6; $starvation_time / 60 / 60 / 24" | bc || ( >&2 echo "$0: Failed to compute starvation time in hours." && exit ) )
 # Determine $poll_freq: how often to poll the file (in seconds). Determined as 1/3 of the starvation time (rounded up to nearest second).
-poll_freq=$( echo "( $starvation_time + 2 ) / 3" | bc || ( >&2 echo "Failed to compute poll frequency." && exit ) )
+poll_freq=$( echo "( $starvation_time + 2 ) / 3" | bc || ( >&2 echo "$0: Failed to compute poll frequency." && exit ) )
 if [[ -n "$profile" ]]
 then
   profile_arg="--profile $profile"
@@ -325,7 +338,6 @@ starve_cmd="aws ec2 ${starve_action}-instances $profile_arg --output text --inst
 # Validate the instance.
 get_current_state() {
   current_state=$( aws ec2 describe-instance-status $profile_arg --output text --include-all-instances --instance-ids $inst_id | grep INSTANCESTATE )
-  exit 1
 }
 
 get_current_state
@@ -373,11 +385,11 @@ trap 'get_current_state && echo $current_state && if [[ "$current_state" =~ stop
 rare_condition() {
   if [[ $debug == 1 ]]
   then
-    >&2 echo "Rare condition: $1"
+    >&2 echo "$0: Rare condition: $1"
     (( rare_cnt++ ))
     if [[ $debug == 1 && $rare_cnt -gt 1000 ]]
     then
-      >&2 echo "Hit a rare condition too many time. Exiting."
+      >&2 echo "$0: Hit a rare condition too many time. Exiting."
       exit 1
     fi
   fi
@@ -410,103 +422,108 @@ rare_cnt=0  # A count of rare events. If this gets too high, exit if $debug.
 
 
 #
-# Create feeder file
+# Begin feeding and create feeder file
 #
 
 
-# Create feeder file.
+# "Feeding" is launched as a separate process, whose PID is stored in the feeder file.
+feed() {
+  # Poll the feeder file, stopping the instance and keeping it stopped when/while the file is starved, and exiting only if the file is deleted.
+
+  while true
+  do
+
+    # Poll feeder file continuously until it is starved.
+    
+    [[ $debug == 0 ]] || printf "Polling for starvation: "
+    while ( wait_on_feeder $poll_freq; is_fed )
+    do
+      [[ $debug == 0 ]] || printf '.'
+    done
+    [[ $debug == 0 ]] || (echo && echo "$feeder_file is starved. Stopping $inst_id.")
+    
+    
+    # Make sure the file remains starved. This avoids a race condition that allows the file to be touched and the instance started.
+    # Without this check, this script could stop the instance immediately after it is started.
+    if ( wait_on_feeder 2; ! is_fed )
+    then
+      
+      
+      # Stop instance (even if it is already stopped), and check success.
+      
+      current_state=$( $starve_cmd | grep CURRENTSTATE )
+      if [[ ! $current_state =~ $starve_state_pattern ]]
+      then
+        # Failed to stop/terminate instance.
+        
+        if [[ ! -n $current_state ]]
+        then
+          >&2 echo "$0: ${starve_action}-instance command failed."
+        else
+          >&2 echo "$0: ${starve_action} command failed to enter '${starve_state_pattern}' state. Got: $current_state"
+        fi
+        
+        # Allow script to continue polling and try again to see if the problem clears up, but let's make sure we delay before trying again.
+        # There will be a poll delay as long as the file exists, but if it was deleted, there will be no delay.
+        # Let's make sure there is some delay here in either case, as an added safety measure against in infinite busy loop.
+        if [[ -e "$feeder_file" ]]
+        then
+          # We'll be doing the poll wait anyway, but just as a precaution:
+          wait_on_feeder 3
+        else
+          rare_condition
+          sleep 5
+          # Note that while sleeping the script is not responsive to signals, but this is an error scenario anyway.
+        fi
+        
+      else
+        # Instance has been stopped/terminated (or is stopping/shutting-down).
+      
+        # If file was deleted, exit.
+        if [[ ! -e "$feeder_file" ]]
+        then
+          echo "File $feeder_file was deleted. Instance $inst_id is $starve_state_pattern."
+          echo "Exiting gracefully and relinquishing responsibility for instance."
+          exit 0
+        fi
+        
+        # Wait until file is touched again (indicating that instance may have been started) (or timeout after -t seconds, just in case we miss it or weren't informed).
+        [[ $debug == 0 ]] || echo "Watching file $feeder_file"
+        wait_on_feeder $watch_timeout
+      fi
+    else
+      >&2 echo "$0: Info: Fed in the nick of time."
+    fi
+    
+  done
+}
+
 if [[ -e "$feederr_file" ]]
 then
-  >&2 echo "feeder file \"$feeder_file\" already exists."
+  >&2 echo "$0: Feeder file \"$feeder_file\" already exists."
   exit 1
-else
-  if ! (set -o noclobber; echo $$ > "$feeder_file" ) &> /dev/null
-  then
-    >&2 echo "Cannot create feeder file \"$feeder_file\"."
-    exit 1
-  fi
+fi
+
+# Begin monitoring feeder file in separate process.
+feed &
+pid=$!
+# Create feeder file containing PID of feeder process.
+if ! (set -o noclobber; echo "$pid" > "$feeder_file" ) &> /dev/null
+then
+  >&2 echo "Cannot create feeder file \"$feeder_file\"."
+  kill $pid || >&2 echo "$0: Failed to kill feeder process $pid on failure."
+  exit 1
 fi
 
 
 echo
 echo "-------------------------------------------------------------------------------"
-echo "Instance $inst_id is tied to the file $feeder_file."
+echo "Instance $inst_id is tied to the file $feeder_file (containing the PID of the feeder process)."
 echo "This instance will only be allowed to continue running as long as this file"
-echo "is touched at least every $starvation_time seconds (polled every $poll_freq seconds)".
-echo "Terminate this script cleanly (stopping the instance) by removing $feeder_file".
+echo "is touched at least every $starvation_time seconds (polled every $poll_freq seconds)."
+echo
+echo "Terminate the feeder process cleanly (stopping the instance) by running:"  # (or be seding SIGINT or by removing $feeder_file)
+echo "  > $0 disconnect $feeder_file"
 echo "-------------------------------------------------------------------------------"
 echo
 
-
-#
-# Monitor
-#
-
-# Poll the feeder file, stopping the instance and keeping it stopped when/while the file is starved, and exiting only if the file is deleted.
-
-while true
-do
-
-  # Poll feeder file continuously until it is starved.
-  
-  [[ $debug == 0 ]] || printf "Polling for starvation: "
-  while ( wait_on_feeder $poll_freq; is_fed )
-  do
-    [[ $debug == 0 ]] || printf '.'
-  done
-  [[ $debug == 0 ]] || (echo && echo "$feeder_file is starved. Stopping $inst_id.")
-  
-  
-  # Make sure the file remains starved. This avoids a race condition that allows the file to be touched and the instance started.
-  # Without this check, this script could stop the instance immediately after it is started.
-  if ( wait_on_feeder 2; ! is_fed )
-  then
-    
-    
-    # Stop instance (even if it is already stopped), and check success.
-    
-    current_state=$( $starve_cmd | grep CURRENTSTATE )
-    if [[ ! $current_state =~ $starve_state_pattern ]]
-    then
-      # Failed to stop/terminate instance.
-      
-      if [[ ! -n $current_state ]]
-      then
-        >&2 echo "${starve_action}-instance command failed."
-      else
-        >&2 echo "${starve_action} command failed to enter '${starve_state_pattern}' state. Got: $current_state"
-      fi
-      
-      # Allow script to continue polling and try again to see if the problem clears up, but let's make sure we delay before trying again.
-      # There will be a poll delay as long as the file exists, but if it was deleted, there will be no delay.
-      # Let's make sure there is some delay here in either case, as an added safety measure against in infinite busy loop.
-      if [[ -e "$feeder_file" ]]
-      then
-        # We'll be doing the poll wait anyway, but just as a precaution:
-        wait_on_feeder 3
-      else
-        rare_condition
-        sleep 5
-        # Note that while sleeping the script is not responsive to signals, but this is an error scenario anyway.
-      fi
-      
-    else
-      # Instance has been stopped/terminated (or is stopping/shutting-down).
-    
-      # If file was deleted, exit.
-      if [[ ! -e "$feeder_file" ]]
-      then
-        echo "File $feeder_file was deleted. Instance $inst_id is $starve_state_pattern."
-        echo "Exiting gracefully and relinquishing responsibility for instance."
-        exit 0
-      fi
-      
-      # Wait until file is touched again (indicating that instance may have been started) (or timeout after -t seconds, just in case we miss it or weren't informed).
-      [[ $debug == 0 ]] || echo "Watching file $feeder_file"
-      wait_on_feeder $watch_timeout
-    fi
-  else
-    >&2 echo "Info: Fed in the nick of time."
-  fi
-  
-done
