Finished initial working support for starting/stopping F1. Created a web component to show an EC2 instance state. Added EC2 feeding in fpgaServer.js and server.py. Patched an issue for wheel events with interactjs and new Chrome. Added Mandelbrot favicon. Enabled apps w/ no launch script. In terraform deployment, opened port 80 and added a password that saves on the server. Added mechanism to check password in server.py.

diff --git a/framework/aws/ec2_instance_feeder b/framework/aws/ec2_instance_feeder
--- a/framework/aws/ec2_instance_feeder
+++ b/framework/aws/ec2_instance_feeder
@@ -343,10 +343,10 @@ get_current_state() {
 get_current_state
 if [[ ! -n "$current_state" ]]
 then
-  >&2 echo "Failed to acquire status of instance."
+  >&2 echo "$0: Failed to acquire status of instance."
   exit 1
 else
-  >&2 echo "Current state of instance: $current_state"
+  echo "$0: Current state of instance: $current_state"
 fi
 
 # Make sure the stop command will work.
@@ -505,6 +505,7 @@ then
 fi
 
 # Begin monitoring feeder file in separate process.
+echo "$0: DEBUG: starting feeder."
 feed &
 pid=$!
 # Create feeder file containing PID of feeder process.
